package de.pantastix.project.ui.screens

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.ContentCopy
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalClipboardManager
import androidx.compose.ui.text.AnnotatedString
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import de.pantastix.project.shared.resources.MR
import dev.icerock.moko.resources.compose.stringResource

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun SupabaseGuideScreen(onBack: () -> Unit) {
    val clipboardManager = LocalClipboardManager.current
    val sqlBefehle = """
        DROP VIEW IF EXISTS public."PokemonCardInfoView";
        DROP TABLE IF EXISTS public."PortfolioSnapshotItem";
        DROP TABLE IF EXISTS public."PortfolioSnapshot";
        DROP TABLE IF EXISTS public."PokemonCardEntity";
        DROP TABLE IF EXISTS public."SetEntity";
        DROP TABLE IF EXISTS public."TypeReference";
        DROP TABLE IF EXISTS public.schema_version;

        CREATE TABLE public."SetEntity" (
            "setId" TEXT PRIMARY KEY,
            "abbreviation" TEXT,
            "nameLocal" TEXT NOT NULL,
            "nameEn" TEXT NOT NULL,
            "logoUrl" TEXT,
            "cardCountOfficial" INTEGER NOT NULL,
            "cardCountTotal" INTEGER NOT NULL,
            "releaseDate" TEXT
        );

        CREATE TABLE public."PokemonCardEntity" (
            "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "setId" TEXT REFERENCES public."SetEntity"("setId") ON DELETE CASCADE,
            "tcgDexCardId" TEXT NOT NULL,
            "nameLocal" TEXT NOT NULL,
            "nameEn" TEXT NOT NULL,
            "language" TEXT NOT NULL,
            "localId" TEXT NOT NULL,
            "imageUrl" TEXT,
            "cardMarketLink" TEXT,
            "ownedCopies" INTEGER NOT NULL DEFAULT 1,
            "notes" TEXT,
            "rarity" TEXT,
            "hp" INTEGER,
            "types" TEXT,
            "illustrator" TEXT,
            "stage" TEXT,
            "retreatCost" INTEGER,
            "regulationMark" TEXT,
            "currentPrice" DOUBLE PRECISION,
            "lastPriceUpdate" TEXT,
            "selectedPriceSource" TEXT,
            "variantsJson" TEXT,
            "abilitiesJson" TEXT,
            "attacksJson" TEXT,
            "legalJson" TEXT,
            "gradedCopiesJson" TEXT,
            UNIQUE("tcgDexCardId", "language")
        );

        CREATE OR REPLACE VIEW public."PokemonCardInfoView" AS
        SELECT
            P."id",
            P."tcgDexCardId",
            P."language",
            P."nameLocal",
            S."nameLocal" AS "setName",
            P."imageUrl",
            P."ownedCopies",
            P."currentPrice",
            P."selectedPriceSource",
            P."lastPriceUpdate" 
        FROM
            public."PokemonCardEntity" AS P
        JOIN
            public."SetEntity" AS S ON P."setId" = S."setId";
            
        CREATE TABLE public.schema_version (
            id INT PRIMARY KEY DEFAULT 1,
            version INT NOT NULL,
            CONSTRAINT one_row CHECK (id = 1)
        );

        -- Start auf Version 3 (PSA Ratings & Snapshots)
        INSERT INTO public.schema_version (id, version) VALUES (1, 3);

        CREATE TABLE public."TypeReference" (
            "id" TEXT PRIMARY KEY,
            "name_de" TEXT NOT NULL,
            "name_en" TEXT NOT NULL,
            "name_fr" TEXT,
            "name_es" TEXT,
            "name_it" TEXT,
            "name_pt" TEXT,
            "name_jp" TEXT
        );

        INSERT INTO public."TypeReference" (id, name_de, name_en, name_fr, name_jp) VALUES 
        ('water', 'Wasser', 'Water', 'Eau', '水'),
        ('fire', 'Feuer', 'Fire', 'Feu', '炎'),
        ('grass', 'Pflanze', 'Grass', 'Plante', '草'),
        ('lightning', 'Elektro', 'Lightning', 'Électrique', '雷'),
        ('psychic', 'Psycho', 'Psychic', 'Psy', '超'),
        ('fighting', 'Kampf', 'Fighting', 'Lucha', '闘'),
        ('darkness', 'Unlicht', 'Darkness', 'Obscurité', '悪'),
        ('metal', 'Metall', 'Metal', 'Métal', '鋼'),
        ('dragon', 'Drache', 'Dragon', 'Dragon', '竜'),
        ('colorless', 'Farblos', 'Colorless', 'Incolore', '無'),
        ('fairy', 'Fee', 'Fairy', 'Fée', 'フェアリー');

        CREATE TABLE public."PortfolioSnapshot" (
            "date" DATE PRIMARY KEY,
            "totalValue" DOUBLE PRECISION NOT NULL,
            "totalRawValue" DOUBLE PRECISION NOT NULL,
            "totalGradedValue" DOUBLE PRECISION NOT NULL,
            "cardCount" INTEGER NOT NULL,
            "updatedAt" TIMESTAMPTZ DEFAULT NOW()
        );

        CREATE TABLE public."PortfolioSnapshotItem" (
            "date" DATE NOT NULL REFERENCES public."PortfolioSnapshot"("date") ON DELETE CASCADE,
            "cardId" BIGINT NOT NULL,
            "nameLocal" TEXT NOT NULL,
            "setName" TEXT NOT NULL,
            "imageUrl" TEXT,
            "rawPrice" DOUBLE PRECISION,
            "rowCount" INTEGER NOT NULL,
            "gradedCopiesJson" TEXT,
            PRIMARY KEY ("date", "cardId")
        );

        CREATE OR REPLACE FUNCTION public.execute_migration(sql_command TEXT)
        RETURNS void AS $$
        BEGIN
            EXECUTE sql_command;
        END;
        $$ LANGUAGE plpgsql SECURITY DEFINER;
        
        GRANT EXECUTE ON FUNCTION public.execute_migration(TEXT) TO postgres;
    """.trimIndent()

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text(stringResource(MR.strings.guide_title)) },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(
                            imageVector = Icons.AutoMirrored.Filled.ArrowBack,
                            contentDescription = stringResource(MR.strings.guide_back_button_desc)
                        )
                    }
                }
            )
        }
    ) { paddingValues ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(paddingValues)
                .verticalScroll(rememberScrollState())
                .padding(16.dp),
            verticalArrangement = Arrangement.spacedBy(24.dp)
        ) {
            AnleitungSchritt(
                nummer = 1,
                titel = stringResource(MR.strings.guide_step1_title),
                beschreibung = stringResource(MR.strings.guide_step1_desc)
            )

            AnleitungSchritt(
                nummer = 2,
                titel = stringResource(MR.strings.guide_step2_title),
                beschreibung = stringResource(MR.strings.guide_step2_desc)
            )

            Surface(
                modifier = Modifier.fillMaxWidth(),
                shape = MaterialTheme.shapes.medium,
                color = MaterialTheme.colorScheme.surfaceVariant,
                contentColor = MaterialTheme.colorScheme.onSurfaceVariant
            ) {
                Column {
                    Text(
                        text = sqlBefehle,
                        modifier = Modifier.padding(16.dp),
                        fontFamily = FontFamily.Monospace
                    )
                    Box(modifier = Modifier.fillMaxWidth().padding(bottom = 8.dp, end = 8.dp)) {
                        Button(
                            onClick = {
                                clipboardManager.setText(AnnotatedString(sqlBefehle))
                            },
                            modifier = Modifier.align(Alignment.CenterEnd)
                        ) {
                            Icon(
                                Icons.Default.ContentCopy,
                                contentDescription = stringResource(MR.strings.guide_copy_sql_button_desc),
                                modifier = Modifier.size(18.dp)
                            )
                            Spacer(Modifier.width(8.dp))
                            Text(stringResource(MR.strings.guide_copy_sql_button))
                        }
                    }
                }
            }

            AnleitungSchritt(
                nummer = 3,
                titel = stringResource(MR.strings.guide_step3_title),
                beschreibung = stringResource(MR.strings.guide_step3_desc)
            )

            AnleitungSchritt(
                nummer = 4,
                titel = stringResource(MR.strings.guide_step4_title),
                beschreibung = stringResource(MR.strings.guide_step4_desc)
            )
        }
    }
}

@Composable
private fun AnleitungSchritt(nummer: Int, titel: String, beschreibung: String) {
    Column(verticalArrangement = Arrangement.spacedBy(4.dp)) {
        Text(
            text = "${stringResource(MR.strings.guide_step_prefix)} $nummer: $titel",
            style = MaterialTheme.typography.titleLarge,
            fontWeight = FontWeight.Bold
        )
        Text(
            text = beschreibung,
            style = MaterialTheme.typography.bodyMedium
        )
    }
}